In [1]:
import tensorflow as tf
tf.__version__


'2.20.0'

In [4]:
scalar = tf.constant(7)
print(scalar) 

tf.Tensor(7, shape=(), dtype=int32)


In [5]:
vector = tf.constant([10, 2])
print("Vector:", vector)

Vector: tf.Tensor([10  2], shape=(2,), dtype=int32)


In [6]:
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:", matrix)

Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [7]:
print("Shape:",matrix.shape)
print("Rank:",tf.rank(matrix))
print("Size:",tf.size(matrix))

Shape: (2, 2)
Rank: tf.Tensor(2, shape=(), dtype=int32)
Size: tf.Tensor(4, shape=(), dtype=int32)


In [8]:
A = tf.constant([[1, 2],
                 [3, 4]])

B = tf.constant([[5, 6],
                 [7, 8]])

print("A + B:", tf.add(A, B))
print("A - B:", tf.subtract(A, B))


A + B: tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
A - B: tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)


In [9]:
scalar_mul = tf.multiply(A, 3)
print("Scalar Multiplication:\n", scalar_mul)


Scalar Multiplication:
 tf.Tensor(
[[ 3  6]
 [ 9 12]], shape=(2, 2), dtype=int32)


In [10]:
matmul = tf.matmul(A, B)
print("Matrix Multiplication:\n", matmul)


Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [12]:
det = tf.linalg.det(tf.cast(A, tf.float32))
print("Determinant:", det)



Determinant: tf.Tensor(-2.0, shape=(), dtype=float32)


In [16]:
vector = tf.constant([3.0, 4.0])

l2_norm = tf.norm(vector, ord=2)
l1_norm = tf.norm(vector, ord=1)

print("L2 Norm:", l2_norm)
print("L1 Norm:", l1_norm)


L2 Norm: tf.Tensor(5.0, shape=(), dtype=float32)
L1 Norm: tf.Tensor(7.0, shape=(), dtype=float32)


In [17]:
A = tf.constant([[3.0, 1.0],
                 [1.0, 2.0]])

B = tf.constant([[9.0],
                 [8.0]])

X = tf.linalg.solve(A, B)
print("Solution X:\n", X)


Solution X:
 tf.Tensor(
[[2.]
 [3.]], shape=(2, 1), dtype=float32)


In [21]:
A = tf.constant([[2.0, 0.0],
                 [0.0, 2.0]])

power = tf.linalg.matmul(A, A)
print("Matrix Power A^2:\n", power)


Matrix Power A^2:
 tf.Tensor(
[[4. 0.]
 [0. 4.]], shape=(2, 2), dtype=float32)


Write a program to implement AND OR gates using Perceptron.



In [ ]:


def perceptron_AND(x1, x2):
    w1 = 1
    w2 = 1
    bias = -1.5
    net = w1*x1 + w2*x2 + bias
    if net >= 0:
        return 1
    else:
        return 0

print("AND Gate")
inputs = [(0,0), (0,1), (1,0), (1,1)]
for x1, x2 in inputs:
    print(f"{x1} AND {x2} = {perceptron_AND(x1, x2)}")


AND Gate
0 AND 0 = 0
0 AND 1 = 0
1 AND 0 = 0
1 AND 1 = 1


In [24]:
def perceptron_OR(x1, x2):
    w1 = 1
    w2 = 1
    bias = -0.5
    net = w1*x1 + w2*x2 + bias
    if net >= 0:
        return 1
    else:
        return 0

print("AND Gate")
inputs = [(0,0), (0,1), (1,0), (1,1)]
for x1, x2 in inputs:
    print(f"{x1} OR {x2} = {perceptron_OR(x1, x2)}")

AND Gate
0 OR 0 = 0
0 OR 1 = 1
1 OR 0 = 1
1 OR 1 = 1


Implementation of XOR Problem using PyTorch Neural Network.

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim


In [3]:
X = torch.tensor([[0.,0.],
                  [0.,1.],
                  [1.,0.],
                  [1.,1.]])

Y = torch.tensor([[0.],
                  [1.],
                  [1.],
                  [0.]])

class XORNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2, 2)
        self.fc2 = nn.Linear(2, 1)

    def forward(self, x):
        x = torch.sigmoid(self.fc1(x))
        x = torch.sigmoid(self.fc2(x))
        return x

model = XORNet()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.1)

for epoch in range(5000):
    optimizer.zero_grad()
    output = model(X)
    loss = criterion(output, Y)
    loss.backward()
    optimizer.step()

print(torch.round(model(X)))


tensor([[0.],
        [1.],
        [1.],
        [1.]], grad_fn=<RoundBackward0>)


5) Implement Simple below Neural Network to solve regression problem.

In [40]:
import torch
import torch.nn as nn
import torch.optim as optim


In [ ]:

X = torch.tensor([[1., 2.],
                  [2., 1.],
                  [3., 4.],
                  [4., 3.]], dtype=torch.float32)

Y = torch.tensor([[8.],
                  [7.],
                  [18.],
                  [17.]], dtype=torch.float32)


In [ ]:
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()

        self.hidden = nn.Linear(2, 2)
        

        self.output = nn.Linear(2, 1)
        
    def forward(self, x):
        h = torch.relu(self.hidden(x))   
        y = self.output(h)               
        return y


In [ ]:
model = SimpleNN()

criterion = nn.MSELoss()    
optimizer = optim.SGD(model.parameters(), lr=0.01)


In [44]:
epochs = 2000

for epoch in range(epochs):
    optimizer.zero_grad()
    
    predictions = model(X)
    loss = criterion(predictions, Y)
    
    loss.backward()
    optimizer.step()
    
    if (epoch + 1) % 500 == 0:
        print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")


Epoch 500, Loss: 0.3496
Epoch 1000, Loss: 0.0278
Epoch 1500, Loss: 0.0021
Epoch 2000, Loss: 0.0002


In [45]:
with torch.no_grad():
    test_input = torch.tensor([[5., 6.]])
    output = model(test_input)
    print("Predicted output:", output.item())


Predicted output: 27.97382354736328
